# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
env_files:
  github_token: ~/dev/dns-heaven/github_token
builds:
  - main: cmd/dns-heaven/main.go
    binary: dns-heaven
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: |-
      -X main.Version={{.Version}}

brews:
  - name: dns-heaven
    url_template: "https://github.com/kcaebe/dns-heaven/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/kcaebe/dns-heaven"
    description: "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
    repository:
      owner: kcaebe
      name: homebrew-dns-heaven
      branch: main
    folder: Formula
    dependencies:
      - name: go
    service: |
      run bin/"dns-heaven"
      keep_alive true
      requires_root true
    test: |
      system 'bin/"dns-heaven" -version'
